# Generated by Django 2.1.2 on 2019-04-14 20:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('messages', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MidiFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('pitch_class_variability', models.FloatField(default=0)),
                ('major_or_minor', models.FloatField(default=0)),
                ('most_common_melodic_interval', models.FloatField(default=0)),
                ('mean_melodic_interval', models.FloatField(default=0)),
                ('amount_of_arpeggiation', models.FloatField(default=0)),
                ('repeated_notes', models.FloatField(default=0)),
                ('chromatic_motion', models.FloatField(default=0)),
                ('melodic_thirds', models.FloatField(default=0)),
                ('vertical_thirds', models.FloatField(default=0)),
                ('mean_tempo', models.FloatField(default=0)),
                ('duration_in_seconds', models.FloatField(default=0)),
                ('note_density', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='midi',
            name='filter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.MidiFilter'),
        ),
    ]
