# Generated by Django 2.1.1 on 2018-10-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Midi',
        ),
    ]
