# Generated by Django 2.1.2 on 2019-08-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midi',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='midi',
            name='filter',
        ),
        migrations.DeleteModel(
            name='MidiFilter',
        ),
    ]
